name: Branch Protection Rules

on:
  # This workflow is triggered manually by repository admins
  workflow_dispatch:

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Branch Protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Get default branch
            const { data: repository } = await github.rest.repos.get({
              owner,
              repo,
            });
            
            const branch = repository.default_branch;
            
            // Setup branch protection rules
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts: ['validate']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1
              },
              restrictions: null
            });